# Generated by Django 4.2.5 on 2023-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="store_custo_last_na_e6a359_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store_customers",
        ),
    ]
